const SETTINGS_SCHEMA = [
  {
    key: 'gridCols',
    label: '每行列数',
    type: 'number',
    group: '显示',
    default: 5,
    min: 1, max: 32, step: 1,
    recommendedMax: 12,
    description: '网格中每行显示几张缩略图。',
    recommend: '5 列适合宽屏，3-4 列适合窄屏。',
    lowImpact: '列数过少会占用更多垂直空间。',
    highImpact: '列数过多会导致图片过小。',
    immediate: false,
  },
  {
    key: 'visibleRows',
    label: '可见行数',
    type: 'number',
    group: '显示',
    default: 2,
    min: 1, max: 20, step: 1,
    recommendedMax: 6,
    description: '不滚动时可见几行缩略图。首屏图片数 = 列数 × 行数。',
    recommend: '2 行可在不展开时看到足够图片。',
    lowImpact: '行数过少看不到足够图片。',
    highImpact: '行数过多会占用页面空间。',
    immediate: false,
  },
  {
    key: 'thumbWidth',
    label: '缩略图宽度',
    type: 'number',
    group: '显示',
    default: 110,
    min: 60, max: 320, step: 10,
    unit: 'px',
    description: '每张缩略图的宽度。',
    recommend: '110px 适合列表页紧凑显示。',
    lowImpact: '宽度太小看不清图片内容。',
    highImpact: '宽度太大会让网格变得很宽。',
    immediate: false,
  },
  {
    key: 'thumbHeight',
    label: '缩略图高度',
    type: 'number',
    group: '显示',
    default: 82,
    min: 50, max: 240, step: 1,
    unit: 'px',
    description: '每张缩略图的高度。',
    recommend: '82px 与 110px 宽度搭配比例合适。',
    immediate: false,
  },
  {
    key: 'gridGap',
    label: '图片间距',
    type: 'number',
    group: '显示',
    default: 6,
    min: 0, max: 20, step: 1,
    unit: 'px',
    description: '相邻缩略图之间的间隙。',
    immediate: false,
  },
  {
    key: 'maxImagesPerPost',
    label: '抓取上限',
    type: 'number',
    group: '加载',
    default: 100,
    min: 10, max: 5000, step: 10,
    recommendedMax: 500,
    description: '从帖子正文最多提取多少张候选图片。',
    recommend: '100 张足够覆盖大部分帖子。',
    lowImpact: '上限太低可能漏掉图片。',
    highImpact: '上限太高会消耗更多流量和内存。',
    immediate: false,
  },
  {
    key: 'maxDisplayPerPost',
    label: '显示上限',
    type: 'number',
    group: '加载',
    default: 100,
    min: 10, max: 5000, step: 10,
    recommendedMax: 500,
    description: '每篇帖子最多显示多少张缩略图。',
    immediate: false,
  },
  {
    // New key leaves the earlier default-on value in storage inert after upgrade.
    key: 'autoLoadOffscreenFirstRowsEnabled',
    label: '屏外首批自动加载',
    type: 'boolean',
    group: '加载',
    default: false,
    description: '不滚动页面也会以后台优先级加载每帖首批图片，张数由每行列数 × 可见行数决定。',
    recommend: '开启后当前列表页的帖子会逐步加载首批图片。',
    highImpact: '列表页帖子很多时会增加正文、图片及 TXT 附件请求。',
    immediate: false,
  },
  {
    key: 'firstScreenConcurrency',
    label: '弱图可见并发',
    type: 'number',
    group: '加载',
    default: 3,
    min: 1, max: 128, step: 1,
    recommendedMax: 30,
    description: '普通/弱图在首屏或进入真实可视范围后，最多同时加载多少张；重图使用独立并发。',
    recommend: '3 适合保守环境；也可使用弱图加载预设快速调整。',
    lowImpact: '并发太低会让当前视线内的图片逐张等待。',
    highImpact: '并发太高可能触发浏览器限制。',
    applyMode: 'live',
  },
  {
    key: 'viewportPriorityReservedSlots',
    label: '可视范围保留槽位',
    type: 'number',
    group: '加载',
    default: 2,
    min: 0, max: 128, step: 1,
    recommendedMax: 16,
    description: '为真实可见图片和手动重试保留多少全局槽位；离屏任务至少保留 1 路持续推进。0 表示不额外保留。',
    recommend: '默认 2；弱图并发提高时可同步提高，预设会自动协调。',
    lowImpact: '过低时离屏慢图可能先占满槽位，让可见图等待。',
    highImpact: '过高时离屏预加载吞吐会下降，但不会完全停止。',
    applyMode: 'live',
  },
  {
    key: 'backgroundConcurrency',
    label: '普图后台并发',
    type: 'number',
    group: '加载',
    default: 1,
    min: 1, max: 128, step: 1,
    recommendedMax: 24,
    description: '后台补齐时普通图床同时加载多少张图片；重图图床使用独立并发。',
    applyMode: 'live',
  },
  {
    key: 'backgroundSpeed',
    label: '后台加载速度',
    type: 'select',
    group: '加载',
    default: 'normal',
    options: [
      { value: 'extreme', label: '极速 (20ms)' },
      { value: 'veryfast', label: '很快 (50ms)' },
      { value: 'fast', label: '快速 (100ms)' },
      { value: 'normal', label: '平衡 (300ms)' },
      { value: 'slow', label: '温和 (800ms)' },
    ],
    description: '后台逐张加载图片的间隔速度。',
    recommend: '平衡模式兼顾速度和性能。',
    highImpact: '快速模式可能增加浏览器负载。',
    applyMode: 'live',
  },
  {
    key: 'imageTimeout',
    label: '图片超时',
    type: 'number',
    group: '加载',
    default: 15000,
    min: 1000, max: 180000, step: 1000,
    recommendedMax: 60000,
    unit: 'ms',
    description: '单张图片加载超时时间，超时后视为加载失败。',
    recommend: '15000ms 通常足够加载大部分图片。',
    lowImpact: '超时太短正常图片也可能失败。',
    highImpact: '超时太长会拖慢整体加载。',
    applyMode: 'live',
  },
  {
    key: 'pauseWhenHidden',
    label: '标签页不可见时暂停',
    type: 'boolean',
    group: '加载',
    default: true,
    description: '开启时切到其他标签页会暂停后台图片加载；关闭后标签页隐藏时继续加载，但不影响并发和速度设置。',
    immediate: false,
  },
  {
    key: 'skipServiceThreads',
    label: '跳过置顶/版务帖',
    type: 'boolean',
    group: '加载',
    default: true,
    description: '扫描列表页时跳过置顶、公告、版规、服务大厅、教程等非资源主题。',
    recommend: '建议开启，可减少无效抓取并改善长列表页滚动体验。',
    immediate: false,
  },
  {
    key: 'animatedThumbnailMode',
    label: '动图缩略图',
    type: 'select',
    group: '显示',
    default: 'still',
    options: [
      { value: 'still', label: '静帧（悬停播放）' },
      { value: 'play', label: '始终播放' }
    ],
    description: '普通图床上的 GIF 动图在列表里显示第一帧，鼠标悬停时播放；点击仍打开原图。',
    recommend: '建议静帧：列表同屏常有几十张动图，全部播放时每一帧都要重新解码、重绘，滚动容易卡顿。',
    highImpact: '始终播放会明显增加滚动时的 CPU 占用，动图多的页面更容易卡顿。',
    immediate: false,
  },
  {
    key: 'heavyImageOptimization',
    label: '重图优化',
    type: 'boolean',
    group: '加载',
    default: true,
    description: '检测到高分辨率重图图床时，均衡模式每帖只加载一行代表图，并从抓取上限内的候选继续补位；轻量缩略模式按普通图显示数量展示；普通图帖不受影响。',
    recommend: '建议开启；轻图页面不受影响，关闭后所有页面按统一显示上限加载。',
    immediate: false,
  },
  {
    key: 'heavyImageConcurrency',
    label: '重图并发',
    type: 'number',
    group: '加载',
    default: 2,
    min: 1, max: 128, step: 1,
    recommendedMax: 12,
    description: '重图优化开启时的用户并发 ceiling；固定模式直接执行，自适应模式只在公开调优参数内变化。',
    recommend: '2 适合高速网络；如果滚动仍卡顿可调回 1。',
    highImpact: '设为较高值会更积极加载重图，可能增加解码和图床压力。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyThumbnailClarity',
    label: '重图缩略清晰度',
    type: 'select',
    group: '加载',
    default: 'balanced',
    options: [
      { value: 'balanced', label: '均衡' },
      { value: 'lightweight', label: '轻量缩略' }
    ],
    description: '仅重图优化开启时有效。均衡按预算在清晰图和毛玻璃之间切换；轻量缩略使用可配置最长边的预览，点击仍打开原图。',
    recommend: '默认均衡；如果更看重满屏重图滚动流畅度，可试轻量缩略。',
    highImpact: '轻量缩略会降低列表缩略图细节，并跳过毛玻璃恢复清晰队列。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    immediate: false,
  },
  {
    key: 'heavyPreviewStarvationWait',
    label: '重图兜底等待',
    type: 'number',
    group: '加载',
    default: 3,
    min: 0, max: 120, step: 1,
    recommendedMax: 24,
    unit: '秒',
    description: '可见毛玻璃长时间被 MP 预算挡住时，等待多少秒后允许重图走更高上限的饥饿兜底恢复。仅重图优化开启时有效。',
    recommend: '3 秒为当前默认（毛玻璃恢复更快）；若满屏重图出现卡顿反弹，可调回 8-16 秒。',
    highImpact: '数值太低会更早恢复超大图，可能增加滚动后的瞬时解码压力。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    immediate: true,
  },
  {
    key: 'heavyPreviewStarvationMP',
    label: '重图兜底上限',
    type: 'number',
    group: '加载',
    default: 820,
    min: 0, max: 10000, step: 20,
    recommendedMax: 2000,
    unit: 'MP',
    description: '饥饿兜底恢复时允许的当前可见区解码量上限。仅重图优化开启时有效。',
    recommend: '820MP 是当前保守值；如果毛玻璃仍残留，可逐步试 1000、1400、1800。',
    highImpact: '数值越高越容易把毛玻璃恢复成清晰图，但也会提高满屏重图时的解码峰值。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    immediate: true,
  },
  {
    key: 'heavyRestoreFastBatchSize',
    label: '重图低压恢复批量',
    type: 'number',
    group: '加载',
    default: 2,
    min: 1, max: 128, step: 1,
    recommendedMax: 6,
    description: '滚动停止且 MP 压力低时，每批最多恢复多少张小/中重图。',
    recommend: '默认 2 保持当前稳定行为；可逐步试 3-4。',
    highImpact: '数值越高，低压时清晰图恢复越快，但同一批解码越集中。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    immediate: true,
  },
  {
    key: 'heavyRestorePressureBatchSize',
    label: '重图高压恢复批量',
    type: 'number',
    group: '加载',
    default: 1,
    min: 1, max: 128, step: 1,
    recommendedMax: 4,
    description: '遇到 soft/hard/ultra 压力或饥饿兜底时，每批最多恢复多少张重图。',
    recommend: '默认 1 最稳；有模糊图缓冲后可试 2。',
    highImpact: '数值越高，毛玻璃更快变清晰，但满屏重图时更容易推高可见 MP 峰值。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    immediate: true,
  },
  {
    key: 'maxRetryPerImage',
    label: '单图重试次数',
    type: 'number',
    group: '高级',
    default: 0,
    min: 0, max: 20, step: 1,
    recommendedMax: 3,
    description: '单张图片加载失败后的重试次数。',
    highImpact: '重试次数太多可能拖慢整体进度。',
    immediate: false,
  },
  {
    key: 'debugLogging',
    label: '调试日志',
    type: 'boolean',
    group: '高级',
    default: false,
    description: '记录详细图片调度与资源提取诊断。默认关闭以减少大量图片加载时的 CPU、控制台和存储开销。',
    recommend: '仅在排查加载问题或导出诊断时临时开启。',
    highImpact: '开启后会增加日志清洗、序列化和本地存储开销。',
    immediate: true,
  },
  {
    key: 'articleFetchConcurrency',
    label: '正文抓取并发',
    type: 'number',
    group: '专家调优',
    default: 3,
    min: 1, max: 32, step: 1,
    recommendedMax: 8,
    description: '同时抓取多少篇帖子正文。正文完成后会立即提交，不再等待整批最慢请求。',
    recommend: '3-6 适合大部分网络；高速网络和高性能电脑可继续提高。',
    highImpact: '过高可能触发论坛限速或增加解析峰值。',
    applyMode: 'live',
  },
  {
    key: 'articleQueueHighWatermark',
    label: '正文队列高水位',
    type: 'number',
    group: '专家调优',
    default: 5,
    min: 1, max: 100, step: 1,
    recommendedMax: 20,
    description: '扫描器一次最多补充多少篇待抓取帖子，worker 空闲后立即补位。',
    applyMode: 'live',
  },
  {
    key: 'articleTimeout',
    label: '正文抓取超时',
    type: 'number',
    group: '专家调优',
    default: 15000,
    min: 1000, max: 180000, step: 1000,
    recommendedMax: 60000,
    unit: 'ms',
    description: '单篇帖子正文的网络超时。',
    applyMode: 'live',
  },
  {
    key: 'articlePrefetchDistance',
    label: '正文预取距离',
    type: 'number',
    group: '专家调优',
    default: 2000,
    min: 0, max: 50000, step: 100,
    recommendedMax: 10000,
    unit: 'px',
    description: '视口上下多远范围内的帖子可以提前进入正文队列。',
    applyMode: 'live',
  },
  {
    key: 'articleCommitBatchSize',
    label: '正文提交批量',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 1, max: 32, step: 1,
    recommendedMax: 8,
    description: '同一帧最多向页面提交多少篇离屏正文结果。可见帖子仍优先立即提交。',
    applyMode: 'live',
  },
  {
    key: 'globalImageConcurrency',
    label: '图片全局总并发',
    type: 'number',
    group: '专家调优',
    default: 0,
    min: 0, max: 256, step: 1,
    recommendedMax: 64,
    description: '普通图与重图合计并发。0 表示自动取弱图可见并发与重图并发之和。',
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostConcurrency',
    label: '普通图同域并发',
    type: 'number',
    group: '专家调优',
    default: 6,
    min: 1, max: 128, step: 1,
    recommendedMax: 30,
    description: '单一普通图床最多同时加载多少张，不再被运行时固定为 6。',
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostAdaptive',
    label: '普通图同域自适应',
    type: 'boolean',
    group: '专家调优',
    default: true,
    description: '开启后按最近失败数量与失败比例降低单域并发，少量失效 URL 不会误伤整台图床；关闭后始终执行“普通图同域并发”。',
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostSoftLimit',
    label: '普通图软降载并发',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 1, max: 128, step: 1,
    recommendedMax: 16,
    enabledWhen: { key: 'ordinaryHostAdaptive', value: true },
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostHardLimit',
    label: '普通图硬降载并发',
    type: 'number',
    group: '专家调优',
    default: 1,
    min: 1, max: 128, step: 1,
    recommendedMax: 8,
    enabledWhen: { key: 'ordinaryHostAdaptive', value: true },
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostSoftFailures',
    label: '普通图软降载阈值',
    type: 'number',
    group: '专家调优',
    default: 3,
    min: 1, max: 100, step: 1,
    recommendedMax: 30,
    enabledWhen: { key: 'ordinaryHostAdaptive', value: true },
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostHardFailures',
    label: '普通图硬降载阈值',
    type: 'number',
    group: '专家调优',
    default: 6,
    min: 1, max: 100, step: 1,
    recommendedMax: 50,
    enabledWhen: { key: 'ordinaryHostAdaptive', value: true },
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostCooldownMs',
    label: '普通图同域冷却',
    type: 'number',
    group: '专家调优',
    default: 30000,
    min: 0, max: 600000, step: 1000,
    recommendedMax: 120000,
    unit: 'ms',
    enabledWhen: { key: 'ordinaryHostAdaptive', value: true },
    applyMode: 'live',
  },
  {
    key: 'ordinaryHostRecoverySuccesses',
    label: '普通图恢复成功数',
    type: 'number',
    group: '专家调优',
    default: 3,
    min: 1, max: 100, step: 1,
    recommendedMax: 30,
    description: '普通图同域冷却后需要连续成功多少次才提前恢复。',
    enabledWhen: { key: 'ordinaryHostAdaptive', value: true },
    applyMode: 'live',
  },
  {
    key: 'viewportPendingLimit',
    label: '视口待加载上限',
    type: 'number',
    group: '专家调优',
    default: 0,
    min: 0, max: 2000, step: 1,
    recommendedMax: 500,
    description: '视口懒加载队列上限。0 表示按布局和后台并发自动计算。',
    applyMode: 'live',
  },
  {
    key: 'backgroundDelayMs',
    label: '后台自定义间隔',
    type: 'number',
    group: '专家调优',
    default: -1,
    min: -1, max: 5000, step: 1,
    recommendedMax: 1000,
    unit: 'ms',
    description: '-1 使用“后台加载速度”预设；0 表示无额外间隔，其余值为自定义间隔。',
    applyMode: 'live',
  },
  {
    key: 'heavySchedulingMode',
    label: '重图调度模式',
    type: 'select',
    group: '专家调优',
    default: 'adaptive',
    options: [
      { value: 'adaptive', label: '自适应' },
      { value: 'fixed', label: '固定并发' }
    ],
    description: '固定模式严格使用重图并发上限；自适应模式在用户配置范围内升降。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyCircuitBreaker',
    label: '重图图床熔断',
    type: 'boolean',
    group: '专家调优',
    default: true,
    description: '关闭后不因图床失败自动开路，仍遵守你设置的并发和超时。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyWarmupConcurrency',
    label: '重图起始并发',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 1, max: 128, step: 1,
    recommendedMax: 12,
    description: '自适应模式下健康未知或恢复初期的起始并发。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyProbeConcurrency',
    label: '重图探针并发',
    type: 'number',
    group: '专家调优',
    default: 1,
    min: 1, max: 128, step: 1,
    recommendedMax: 8,
    description: '图床冷却到期后用于试探恢复的并发。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'ordinaryReservedSlots',
    label: '普通图保留槽位',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 0, max: 128, step: 1,
    recommendedMax: 16,
    description: '混合页面为普通图保留多少总槽。0 表示不保留，不再暗中把重图压到 1 或 3。',
    applyMode: 'live',
  },
  {
    key: 'ordinaryFallbackLimit',
    label: '普通图单槽候选回退',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 0, max: 50, step: 1,
    recommendedMax: 10,
    description: '普通或混合帖子中，一个加载槽最多替换多少个候选。0 表示失败后不自动换候选。',
    applyMode: 'live',
  },
  {
    key: 'heavyImageTimeout',
    label: '重图单候选超时',
    type: 'number',
    group: '专家调优',
    default: 0,
    min: 0, max: 180000, step: 1000,
    recommendedMax: 60000,
    unit: 'ms',
    description: '0 继承“图片超时”；非零时重图使用该值，不再有隐藏 8 秒或 3.5 秒截断。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyFailureThreshold',
    label: '重图连续失败阈值',
    type: 'number',
    group: '专家调优',
    default: 6,
    min: 1, max: 100, step: 1,
    recommendedMax: 30,
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    description: '失败时间窗内达到多少个不同候选失败后进入冷却。',
    applyMode: 'live',
  },
  {
    key: 'heavyFailureWindowMs',
    label: '重图失败时间窗',
    type: 'number',
    group: '专家调优',
    default: 60000,
    min: 1000, max: 600000, step: 1000,
    recommendedMax: 120000,
    unit: 'ms',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    description: '超过时间窗的旧失败不再污染当前图床健康状态。',
    applyMode: 'live',
  },
  {
    key: 'heavyCooldownBaseMs',
    label: '重图基础冷却',
    type: 'number',
    group: '专家调优',
    default: 20000,
    min: 0, max: 600000, step: 1000,
    recommendedMax: 120000,
    unit: 'ms',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyCooldownMaxMs',
    label: '重图最大冷却',
    type: 'number',
    group: '专家调优',
    default: 60000,
    min: 0, max: 1800000, step: 1000,
    recommendedMax: 300000,
    unit: 'ms',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyRampSuccesses',
    label: '重图升槽成功数',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 1, max: 100, step: 1,
    recommendedMax: 20,
    description: '自适应模式每增加一个并发槽需要多少次连续成功。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyRecoverySuccesses',
    label: '重图恢复成功数',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 1, max: 100, step: 1,
    recommendedMax: 20,
    description: '半开探针连续成功多少次后恢复到预热状态。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyFallbackLimit',
    label: '重图单槽候选回退',
    type: 'number',
    group: '专家调优',
    default: 2,
    min: 0, max: 50, step: 1,
    recommendedMax: 10,
    description: '一个加载槽内最多替换多少个候选。图床开路时同域候选等待恢复，不连续冲击。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'imageTaskDeadline',
    label: '图片任务总期限',
    type: 'number',
    group: '专家调优',
    default: 0,
    min: 0, max: 900000, step: 1000,
    recommendedMax: 300000,
    unit: 'ms',
    description: '0 表示不额外限制；非零时限制同一任务多候选串联的总耗时。',
    applyMode: 'live',
  },
  {
    key: 'heavyDecodedBudgetMP',
    label: '重图附近解码预算',
    type: 'number',
    group: '专家调优',
    default: 160,
    min: 0, max: 10000, step: 10,
    recommendedMax: 2000,
    unit: 'MP',
    description: '重图恢复范围内允许保留的解码量。0 表示不使用 MP 上限。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyVisibleBudgetMP',
    label: '重图可见区预算',
    type: 'number',
    group: '专家调优',
    default: 180,
    min: 0, max: 10000, step: 10,
    recommendedMax: 2000,
    unit: 'MP',
    description: '当前可见区允许保留的重图解码量。0 表示不使用 MP 上限。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyDecodedImageLimit',
    label: '清晰重图数量上限',
    type: 'number',
    group: '专家调优',
    default: 8,
    min: 0, max: 128, step: 1,
    recommendedMax: 32,
    description: '附近区域最多保留多少张清晰重图。0 表示不限制数量。',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    applyMode: 'live',
  },
  {
    key: 'heavyLightweightPreviewEdge',
    label: '轻量缩略最长边',
    type: 'number',
    group: '专家调优',
    default: 160,
    min: 32, max: 1024, step: 16,
    recommendedMax: 320,
    unit: 'px',
    enabledWhen: { key: 'heavyImageOptimization', value: true },
    description: '轻量缩略画布的最长边。数值越大越清晰，也更占内存。',
    applyMode: 'live',
  },
  {
    key: 'cacheTTL',
    label: '缓存时间',
    type: 'number',
    group: '高级',
    default: 30,
    min: 1, max: 1440, step: 1,
    recommendedMax: 120,
    unit: '分钟',
    description: '已加载图片 URL 的缓存有效时间。缓存期内不再重新抓取。',
    recommend: '30 分钟适合大部分使用场景。',
    lowImpact: '缓存太短会导致重复抓取。',
    highImpact: '缓存太长可能导致新图片不及时显示。',
    immediate: false,
  },
  {
    key: 'showResourcePanel',
    label: '显示资源栏',
    type: 'boolean',
    group: '资源',
    default: true,
    description: '在列表页右侧空白区显示当前帖子提取到的网盘、ED2K、磁力等资源摘要。',
    recommend: '开启后可直接复制帖子资源链接，无需进入帖子详情页。',
    immediate: false,
  },
  {
    key: 'copyPasswordsWithLinks',
    label: '复制时附带密码',
    type: 'boolean',
    group: '资源',
    default: true,
    description: '复制资源链接时自动附带帖子中识别到的解压密码。',
    recommend: '建议开启，避免下载压缩包后还要回帖查找密码。',
    immediate: true,
  },
];

const ATP_SETTINGS_APPLY_MODES = Object.freeze({
  LIVE: 'live',
  HOT_RELOAD: 'hotReload',
  PAGE_RELOAD: 'pageReload'
});

const ATP_SETTINGS_GROUP_META = Object.freeze({
  '\u4e13\u5bb6\u8c03\u4f18': Object.freeze({ collapsible: true, collapsed: true })
});

function ATPGetSettingsGroupMeta(groupName) {
  return ATP_SETTINGS_GROUP_META[groupName] || {};
}

for (var ATPSettingsSchemaIndex = 0; ATPSettingsSchemaIndex < SETTINGS_SCHEMA.length; ATPSettingsSchemaIndex++) {
  var ATPSettingsSchemaItem = SETTINGS_SCHEMA[ATPSettingsSchemaIndex];
  if (!ATPSettingsSchemaItem.applyMode) {
    ATPSettingsSchemaItem.applyMode = ATPSettingsSchemaItem.immediate === false
      ? ATP_SETTINGS_APPLY_MODES.HOT_RELOAD
      : ATP_SETTINGS_APPLY_MODES.LIVE;
  }
}

function ATPGetSettingApplyMode(settingOrKey, schema) {
  var key = typeof settingOrKey === 'string' ? settingOrKey : settingOrKey && settingOrKey.key;
  if (key === 'enabled' || key === 'siteConfigs') return ATP_SETTINGS_APPLY_MODES.PAGE_RELOAD;
  var item = typeof settingOrKey === 'object' && settingOrKey ? settingOrKey : null;
  var source = Array.isArray(schema) ? schema : SETTINGS_SCHEMA;
  if (!item) {
    for (var i = 0; i < source.length; i++) {
      if (source[i] && source[i].key === key) {
        item = source[i];
        break;
      }
    }
  }
  if (!item) return ATP_SETTINGS_APPLY_MODES.PAGE_RELOAD;
  if (
    item.applyMode === ATP_SETTINGS_APPLY_MODES.LIVE ||
    item.applyMode === ATP_SETTINGS_APPLY_MODES.HOT_RELOAD ||
    item.applyMode === ATP_SETTINGS_APPLY_MODES.PAGE_RELOAD
  ) {
    return item.applyMode;
  }
  return item.immediate === false ? ATP_SETTINGS_APPLY_MODES.HOT_RELOAD : ATP_SETTINGS_APPLY_MODES.LIVE;
}

function ATPGetSettingsApplyMode(keys, schema) {
  var mode = ATP_SETTINGS_APPLY_MODES.LIVE;
  var sourceKeys = Array.isArray(keys) ? keys : [];
  for (var i = 0; i < sourceKeys.length; i++) {
    var itemMode = ATPGetSettingApplyMode(sourceKeys[i], schema);
    if (itemMode === ATP_SETTINGS_APPLY_MODES.PAGE_RELOAD) return itemMode;
    if (itemMode === ATP_SETTINGS_APPLY_MODES.HOT_RELOAD) mode = itemMode;
  }
  return mode;
}

var ATP_ORDINARY_LOAD_PRESET_VALUES = {
  ordinaryGentle: {
    firstScreenConcurrency: 6,
    viewportPriorityReservedSlots: 4,
    backgroundConcurrency: 1,
    ordinaryHostConcurrency: 6,
    ordinaryHostAdaptive: true,
    ordinaryHostSoftLimit: 3,
    ordinaryHostHardLimit: 2,
    ordinaryHostSoftFailures: 4,
    ordinaryHostHardFailures: 8,
    ordinaryHostCooldownMs: 15000,
    ordinaryHostRecoverySuccesses: 2,
    globalImageConcurrency: 0,
    viewportPendingLimit: 24,
    backgroundSpeed: 'normal',
    backgroundDelayMs: -1,
    imageTimeout: 10000,
    imageTaskDeadline: 20000,
    articleFetchConcurrency: 4,
    articleQueueHighWatermark: 6,
    articlePrefetchDistance: 2000,
    articleCommitBatchSize: 2
  },
  ordinaryBalanced: {
    firstScreenConcurrency: 8,
    viewportPriorityReservedSlots: 5,
    backgroundConcurrency: 2,
    ordinaryHostConcurrency: 8,
    ordinaryHostAdaptive: true,
    ordinaryHostSoftLimit: 4,
    ordinaryHostHardLimit: 2,
    ordinaryHostSoftFailures: 5,
    ordinaryHostHardFailures: 10,
    ordinaryHostCooldownMs: 12000,
    ordinaryHostRecoverySuccesses: 2,
    globalImageConcurrency: 0,
    viewportPendingLimit: 24,
    backgroundSpeed: 'normal',
    backgroundDelayMs: -1,
    imageTimeout: 9000,
    imageTaskDeadline: 18000,
    articleFetchConcurrency: 5,
    articleQueueHighWatermark: 8,
    articlePrefetchDistance: 2400,
    articleCommitBatchSize: 2
  },
  ordinaryFast: {
    firstScreenConcurrency: 12,
    viewportPriorityReservedSlots: 7,
    backgroundConcurrency: 2,
    ordinaryHostConcurrency: 10,
    ordinaryHostAdaptive: true,
    ordinaryHostSoftLimit: 5,
    ordinaryHostHardLimit: 2,
    ordinaryHostSoftFailures: 6,
    ordinaryHostHardFailures: 12,
    ordinaryHostCooldownMs: 10000,
    ordinaryHostRecoverySuccesses: 2,
    globalImageConcurrency: 0,
    viewportPendingLimit: 24,
    backgroundSpeed: 'fast',
    backgroundDelayMs: -1,
    imageTimeout: 8000,
    imageTaskDeadline: 16000,
    articleFetchConcurrency: 6,
    articleQueueHighWatermark: 8,
    articlePrefetchDistance: 2800,
    articleCommitBatchSize: 2
  }
};

function ATPGetSettingsPreset(name, schema) {
  var preset = {};
  var source = Array.isArray(schema) ? schema : SETTINGS_SCHEMA;
  var ordinaryValues = ATP_ORDINARY_LOAD_PRESET_VALUES[name];
  if (ordinaryValues) {
    for (var ordinaryIndex = 0; ordinaryIndex < source.length; ordinaryIndex++) {
      var ordinaryItem = source[ordinaryIndex];
      if (!ordinaryItem || !ordinaryItem.key || !Object.prototype.hasOwnProperty.call(ordinaryValues, ordinaryItem.key)) continue;
      preset[ordinaryItem.key] = ordinaryValues[ordinaryItem.key];
    }
    return preset;
  }
  if (name !== 'heavyOriginal') return preset;
  for (var i = 0; i < source.length; i++) {
    var item = source[i];
    if (!item || !item.key) continue;
    var isHeavySetting = item.key.indexOf('heavy') === 0 && item.key !== 'heavyImageOptimization';
    var isSharedHeavySetting = item.key === 'ordinaryReservedSlots' || item.key === 'imageTaskDeadline';
    if (isHeavySetting || isSharedHeavySetting) preset[item.key] = item.default;
  }
  return preset;
}
